name: Build and Push Docker Image

on:
  workflow_dispatch:  #  manual triggering of the workflow
  push:
    branches:
      - add-dockerfile 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: quay.io  #  GH environment

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: quay.io/zizac/prometheus-slurm-exporter:latest